language: minimal

services:
  - docker

before_install:
  - docker pull hadolint/hadolint
  - docker pull centos:7

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      script: make ci
    - stage: deploy
      script: make push-image
      if: branch = master
